name: Build and Push to GHCR (qday-io)

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag for image'
        required: false
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (via PAT)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: your-github-username          # ← 改成你的用户名（不是组织名）
          password: ${{ secrets.GHCR_PAT }}       # ← 你在 Secrets 中添加的 PAT

      - name: Determine tag
        id: vars
        run: |
          TAG="${{ github.event.inputs.tag }}"
          if [ -z "$TAG" ]; then
            if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              TAG="${GITHUB_REF#refs/tags/}"
            else
              TAG="${GITHUB_SHA}"
            fi
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/qday-io/qday-da-node:latest
            ghcr.io/qday-io/qday-da-node:${{ steps.vars.outputs.tag }}
